# Generated by Django 2.2.6 on 2020-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(default='NULL', max_length=3)),
                ('images', models.ImageField(default='NULL', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NULL', max_length=30)),
                ('room_no', models.CharField(default='NULL', max_length=3)),
                ('images', models.ImageField(default='NULL', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='NULL', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NULL', max_length=30)),
                ('images', models.ImageField(default='NULL', upload_to='images/')),
            ],
        ),
    ]
